export const FAKE_DATA = [
  {
    date: "May 29,2024",
    company: "Amazon",
    image: "/amazon.png",
    title: "Senior Data Analyst",
    salary: "$260/month",
    location: "remote",
    bgColor: "#D4F6ED",
    keyPoints: ["Part Time", "Project Based", "Senior Level"],
  },
  {
    date: "April 5, 2023",
    company: "Google",
    image: "/google.png",
    title: "Junior UI/UX Designer",
    salary: "$190/month",
    location: "California, CA",
    bgColor: "#E3DBFA",
    keyPoints: ["Part Time", "Project Based", "Junior Level"],
  },
  {
    date: "June 23, 2023",
    company: "Apple",
    image: "/apple.png",
    title: "Graphic Designer",
    salary: "$100/month",
    location: "San Francisco, CA",
    bgColor: "#FFE1CC",
    keyPoints: ["Part Time", "Practice Tasks"],
  },
  // Duplicated items for carousel length
  {
    date: "May 29,2024",
    company: "Amazon",
    image: "/amazon.png",
    title: "Senior Data Analyst",
    salary: "$260/month",
    location: "remote",
    bgColor: "#D4F6ED",
    keyPoints: ["Part Time", "Project Based", "Senior Level"],
  },
  {
    date: "April 5, 2023",
    company: "Google",
    image: "/google.png",
    title: "Junior UI/UX Designer",
    salary: "$190/month",
    location: "California, CA",
    bgColor: "#E3DBFA",
    keyPoints: ["Part Time", "Project Based", "Junior Level"],
  },
  {
    date: "June 23, 2023",
    company: "Apple",
    image: "/apple.png",
    title: "Graphic Designer",
    salary: "$100/month",
    location: "San Francisco, CA",
    bgColor: "#FFE1CC",
    keyPoints: ["Part Time", "Practice Tasks"],
  },
];
