export const internships = [
  {
    _id: "internship_001",
    title: "Software Engineer Intern",
    slug: "software-engineer-intern",
    description:
      "Join our team to build scalable web applications using React and Node.js.",
    company: "company_123",
    location: "Islamabad",
    salary: 500,
    live: true,
    expiryDate: "2025-06-30T23:59:59.000Z",
    sponsored: false,
    verified: true,
    term: "FULL-TIME",
    duration: 6,
    createdAt: "2025-05-01T09:00:00.000Z",
    applications: 45,
  },
  {
    _id: "internship_002",
    title: "Frontend Developer Intern",
    slug: "frontend-developer-intern",
    description: "Work on modern UI/UX designs with React and Tailwind CSS.",
    company: "company_123",
    location: "Remote",
    salary: 400,
    live: true,
    expiryDate: "2025-07-15T23:59:59.000Z",
    sponsored: true,
    verified: false,
    term: "PART-TIME",
    duration: 4,
    createdAt: "2025-05-10T12:00:00.000Z",
    applications: 30,
  },
  {
    _id: "internship_003",
    title: "Backend Developer Intern",
    slug: "backend-developer-intern",
    description: "Develop APIs and manage databases with Node.js and MongoDB.",
    company: "company_123",
    location: "Lahore",
    salary: 450,
    live: false,
    expiryDate: "2025-05-01T23:59:59.000Z",
    sponsored: false,
    verified: true,
    term: "FULL-TIME",
    duration: 5,
    createdAt: "2025-04-15T15:00:00.000Z",
    applications: 20,
  },
  {
    _id: "internship_004",
    title: "AI Developer Intern",
    slug: "ai-developer-intern",
    description:
      "Contribute to AI-driven projects using Python and TensorFlow.",
    company: "company_123",
    location: "Karachi",
    salary: 600,
    live: true,
    expiryDate: "2025-08-01T23:59:59.000Z",
    sponsored: false,
    verified: false,
    term: "FULL-TIME",
    duration: 6,
    createdAt: "2025-05-12T10:00:00.000Z",
    applications: 25,
  },
  {
    _id: "internship_005",
    title: "Full Stack Intern",
    slug: "full-stack-intern",
    description: "Build end-to-end web applications with MERN stack.",
    company: "company_123",
    location: "Remote",
    salary: 500,
    live: true,
    expiryDate: "2025-07-30T23:59:59.000Z",
    sponsored: true,
    verified: true,
    term: "PART-TIME",
    duration: 3,
    createdAt: "2025-05-15T14:00:00.000Z",
    applications: 35,
  },
];
