export const user = {
  name: "Aqib Shoaib",
  email: "example@gmail.com",
  password: "test1234",
  role: "COMPANY",
  profileImage: "/user.png",
  bio: "Aspiring Software Engineer with a passion for building scalable and efficient web applications.",
  headline: "Software Engineering Intern",
  website: "http://localhost:5173/",
  phoneNumber: "+923046164841",
  skills: ["React.js", "Node.js", "Express.js", "MongoDB", "Tailwind CSS"],
  education: [
    {
      school: "UET Taxila",
      degree: "BS Software Engineering",
      year: "Senior (4th year)",
    },
  ],
  resume: "/resume.pdf",
  industry: "Tech",
  location: "Islamabad",
  verified: true,
  passwordResetToken: null,
  passwordResetExpires: null,
  otp: null,
  otpExpires: null,
  allowLogin: false,
  isActive: true,
  createdAt: "2025-05-15T23:50:00.000Z",
  updatedAt: "2025-05-15T23:50:00.000Z",
};
